### ISSUE TITLE
vscode 调试export_timvx 源码提示 “Unable to connect to server!”

### ISSUE THREAD

**Issue by zjd1988** [VeriSilicon/acuitylite#11]
@thezha 
      你好，按照readme编译export_timvx源码，同时在vscode的launch.json 设置环境变量，但是F5 调试，输出 “Unable to connect to server!”，但是在命令行下程序，能正常运行，这是为什么呢？

![企业微信截图_16740211772772](https://user-images.githubusercontent.com/7134030/213095097-908bae29-7b8d-4f90-8f93-3f632fa599c6.png)

**Comment by geneyoung** [comment]
@zjd1988 
你好，你再试试跑app的时候加一个环境变量“name”为DISABLE_IDE_DEBUG, “value”为1呢？

**Comment by zjd1988** [comment]
@geneyoung 刚试了下，可以了，谢谢。
