### ISSUE TITLE
Is docker file content correct to install version 6.21.0?

### ISSUE THREAD

**Issue by 0b11101010** [VeriSilicon/acuitylite#17]
Hello,
I couldn't install acuitylite 6.21.0 using a fresh virtual machine or using a conda environment. There are pip packages listed inside the docker file for ubuntu 22.04. Is the content fresh for version 6.21.0?

For example:
ERROR: Cannot install acuitylite==6.21.0 and ruamel.yaml==0.16.0 because these package versions have conflicting dependencies.

I also get the following ruamel.yaml error when I try to install using a conda environment.
 note: This error originates from a subprocess, and is likely not a problem with pip.
 ERROR: Failed building wheel for ruamel.yaml

**Comment by lileiigithub** [comment]
You can try the command: pip install acuitylite==6.21.0 --no-deps

**Comment by 0b11101010** [comment]
Hello @lileiigithub,
Thanks for the suggestion. Demo scripts run successfully on my conda environment now.
