### ISSUE TITLE
acuitylite is NOT in PYPI

### ISSUE THREAD

**Issue by Takugo** [VeriSilicon/acuitylite#2]
Hi guys, 
Thanks for your awesome work after acuity toolkits, but 
`pip install acuitylite`
is still not working, and it shows that acuitylite is not in **PYPI**
```
ERROR: Could not find a version that satisfies the requirement acuitylite (from versions: none)
ERROR: No matching distribution found for acuitylite
```

How to get this tool ?

**Comment by michaelnguyen11** [comment]
I met same issue before, then I downloaded acuitylite wheel file directly at https://pypi.org/project/acuitylite/#files and install it normally.

**Comment by thezha** [comment]
Currently, acuitylite is only available for Ubuntu 18.04 and not other versions of linux distro or windows. We are working on adding them in the future.

**Comment by lileiigithub** [comment]
The Acuitylite only has the package for python3.8 now. Maybe should make sure your python version is python3.8.

**Comment by michaelnguyen11** [comment]
I used ```pip install acuitylite``` to install acuitylite. However, it installed a lot of tensorflow version, then finalize with tensorflow 2.3.4, it's so annoying.

Environment : Ubuntu 18.04, conda environment with python 3.8.12 only.

```
Collecting tensorflow<=2.6.0,>=2.3.0
  Downloading tensorflow-2.5.2-cp38-cp38-manylinux2010_x86_64.whl (454.5 MB)
     |████████████████████████████████| 454.5 MB 4.1 kB/s 
Collecting keras-nightly~=2.5.0.dev
  Using cached keras_nightly-2.5.0.dev2021032900-py2.py3-none-any.whl (1.2 MB)
Collecting tensorflow-estimator<2.6.0,>=2.5.0
  Using cached tensorflow_estimator-2.5.0-py2.py3-none-any.whl (462 kB)
Collecting grpcio~=1.34.0
  Downloading grpcio-1.34.1-cp38-cp38-manylinux2014_x86_64.whl (4.0 MB)
     |████████████████████████████████| 4.0 MB 6.4 MB/s 
Collecting tensorflow<=2.6.0,>=2.3.0
  Downloading tensorflow-2.5.1-cp38-cp38-manylinux2010_x86_64.whl (454.5 MB)
     |████████████████████████████████| 454.5 MB 509 bytes/s 
  Downloading tensorflow-2.5.0-cp38-cp38-manylinux2010_x86_64.whl (454.4 MB)
     |████████████████████████████████| 454.4 MB 28 kB/s 
  Downloading tensorflow-2.4.4-cp38-cp38-manylinux2010_x86_64.whl (394.6 MB)
     |████████████████████████████████| 394.6 MB 16 kB/s 
Collecting h5py~=2.10.0
  Downloading h5py-2.10.0-cp38-cp38-manylinux1_x86_64.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 6.0 MB/s 
Collecting tensorflow<=2.6.0,>=2.3.0
  Downloading tensorflow-2.4.3-cp38-cp38-manylinux2010_x86_64.whl (394.6 MB)
     |████████████████████████████████| 394.6 MB 22 kB/s 
  Downloading tensorflow-2.4.2-cp38-cp38-manylinux2010_x86_64.whl (394.5 MB)
     |████████████████████████████████| 394.5 MB 1.2 kB/s 
  Downloading tensorflow-2.4.1-cp38-cp38-manylinux2010_x86_64.whl (394.4 MB)
     |████████████████████████████████| 394.4 MB 6.6 kB/s 
  Downloading tensorflow-2.4.0-cp38-cp38-manylinux2010_x86_64.whl (394.8 MB)
     |████████████████████████████████| 394.8 MB 30 kB/s 
  Downloading tensorflow-2.3.4-cp38-cp38-manylinux2010_x86_64.whl (320.7 MB)
     |█████████████████████           | 210.6 MB 3.3 MB/s eta 0:00:34
```

**Comment by lileiigithub** [comment]
Maybe the TensorFlow conflict with your other local python packages. You can try command: pip install acuitylite --no-deps , and install TensorFlow(<=2.6.0,>=2.3.0) independently.

**Comment by Goose-Bomb** [comment]
Can you provide a python 3.9 version package？It's the stable python version on Debian 11.

**Comment by Nullkooland** [comment]
Could you provide a python 3.9 package? It's the stable python version on Debian 11.
@thezha [thezha](https://github.com/thezha)

**Comment by lileiigithub** [comment]
> Could you provide a python 3.9 package? It's the stable python version on Debian 11. @thezha [thezha](https://github.com/thezha)

Thanks for your feedback. we'll support python3.9 for Acuitylite in the near future. But we only test on ubuntu now.
