### ISSUE TITLE
Example are not working

### ISSUE THREAD

**Issue by erichs0608** [VeriSilicon/acuitylite#22]
The examples are not working.

  File "alexnet_darknet_test.py", line 4, in <module>
    from acuitylib.interface.importer import DarknetLoader
ModuleNotFoundError: No module named 'acuitylib.interface'

Do you change the API? By the way there is no 6.27.0 from PIP.

Eric Hsiao

**Comment by lucky26418** [comment]
> The examples are not working.
> 
> File "alexnet_darknet_test.py", line 4, in from acuitylib.interface.importer import DarknetLoader ModuleNotFoundError: No module named 'acuitylib.interface'
> 
> Do you change the API? By the way there is no 6.27.0 from PIP.
> 
> Eric Hsiao

New API 'acuitylib.interface' used since Acuitylite 6.21.0, more details can be found in demos. Please use a higher Acuitylite version and try again.

There is Acuitylite 6.27.0 on PIP, please check and try again.

**Comment by erichs0608** [comment]
Hi.

The docker file that I used is ubuntu20.04+python3.8. I believe you do not update acuitylite package for python3.8. Please add it for python3.8 or remove the docker file that you provide.

builder@5a89bc5735eb:/acuitylite$ pip3 install acuitylite --no-deps
Collecting acuitylite
  Using cached acuitylite-6.20.0-cp38-cp38-manylinux2010_x86_64.whl (178.2 MB)
Installing collected packages: acuitylite
Successfully installed acuitylite-6.20.0
builder@5a89bc5735eb:/acuitylite$

![image](https://github.com/VeriSilicon/acuitylite/assets/11831773/58555c4e-471b-45e4-9f7b-a694e60f6dce)
Eric Hsiao

**Comment by lucky26418** [comment]
please use the corresponding docker what Acuitylite 6.27.0 (or other version) required.
