### ISSUE TITLE
Usefull or just for fun!

### ISSUE THREAD

**Issue by 2050airobert** [VeriSilicon/acuitylite#9]
hi，
1 I don not know what you said below.
"Tips: You can export a TFLite app and using [tflite-vx-delegate](https://github.com/VeriSilicon/tflite-vx-delegate) to run on 2 TIM-VX if the exported TIM-VX app does not meet your requirements."
2 There is a realworld quesion, if I have a more layers and newest tflite model, could I transfer it by this acuitylite tool to generate the testcase of my tflite mode? Or it supports only few and old cnn models?
3 Is there any detailed step to intruduce the use of this tool?
BR

**Comment by 2050airobert** [comment]
hi，any one could help ？ tks

**Comment by lileiigithub** [comment]
Thanks for your feedback. 
1. Acuitylite can export the timvx case directly for TIM-VX,  but when the exporter does something wrong, you can also try exporting tflite model for running on TIM-VX by using tflite-vx-delegate.
2. Acuitylite dependence on tensorflow2.8 in the current version, so it will export the tflite model version of tensorflow2.8.
3. You can refer to the demo and document on https://verisilicon.github.io/acuitylite/.

**Comment by 2050airobert** [comment]
tks，you mean the  tflite-vx-delegate will generate the demo code of   my newest cnn model  just like  what NBG project could do ?  After transfering with tflite-vx-delegate,I can run the demo of my code including pre and post processing of my model ?

**Comment by lileiigithub** [comment]
I think yes, but you can refer to https://github.com/VeriSilicon/tflite-vx-delegate for more info. And you can make an issue for more questions under tflite-vx-delegate repo.

**Comment by 2050airobert** [comment]
I did！
Yet no one answers me such as your kind hearted reply！
https://github.com/VeriSilicon/tflite-vx-delegate/issues/92

**Comment by lileiigithub** [comment]
I am sorry for that. And I will ask for help from others tomorrow workday because I don't know much about tflite-vx-delegate project.
BR

**Comment by 2050airobert** [comment]
I see already.
Thankful to you , you are so nice and hardworking  guy!
Looking forward to you good feedback !

**Comment by 2050airobert** [comment]
hi，
     Why the  number of users of acuitylite tool is so small？  No issues or questions at all！
     I tried some new cnn models converting to int8 model on the a311d NPU with this tools， yet  much error occurs still now！
     Could we assure the tool is situable for nearly  the most of new CNN model all the world？
     If I have a selfdefined yet still format onnx model， could I get the int8 model easily and no error at all？ Right ？
BR

**Comment by geneyoung** [comment]
> hi， Why the number of users of acuitylite tool is so small？ No issues or questions at all！ I tried some new cnn models converting to int8 model on the a311d NPU with this tools， yet much error occurs still now！ Could we assure the tool is situable for nearly the most of new CNN model all the world？ If I have a selfdefined yet still format onnx model， could I get the int8 model easily and no error at all？ Right ？ BR

Hi,
Sorry for you any inconvinence. Generally, our tool can support many popular ONNX models, we don't know what concrete problems you met. Do you crashed at  load/quantize/export stage? could you please paste you error log for us to debug? Thanks in advance for your feedback.
